### ISSUE TITLE
 haven't remove of  not existing domain name

### ISSUE THREAD

**Issue by xl7dev** [TheRook/subbrute#27]
hello,guy

python subbrute.py -c 30 -p snda.com
    mail1.mail.snda.com,NXDOMAIN,
    mail2.mail.snda.com,NXDOMAIN,
    mail3.mail.snda.com,NXDOMAIN,
    mail4.mail.snda.com,NXDOMAIN,
    mail5.mail.snda.com,NXDOMAIN,
    mail6.mail.snda.com,NXDOMAIN,
    mail7.mail.snda.com,NXDOMAIN,
dig snda.com
; <<>> DiG 9.8.3-P1 <<>> mail3.mail.snda.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 47267
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;mail3.mail.snda.com.		IN	A

;; AUTHORITY SECTION:
snda.com.		56	IN	SOA	snda.com. root.ns.snda.com. 20051118 72 36 72 36

;; Query time: 12 msec
;; SERVER: 180.76.76.76#53(180.76.76.76)
;; WHEN: Sat Sep 19 02:24:27 2015
;; MSG SIZE  rcvd: 81

**Comment by TheRook** [comment]
This is an intentional feature of subbrute.

snda.com treats non existent domains as NOERROR.  The  NXDOMAIN is used for non-existent subs of mail.snda.com.    A filter will be implemented for 2nd level subs which do not have the same response as  1st level subs.   For now,  if you don't like the results just use `grep -v NXDOMAIN`

Additionally,  if you use -c, you need to provide a list of open resolvers,  or you will just overwhelm the authoritative. 

-rook

**Comment by xl7dev** [comment]
👌
