### ISSUE TITLE
Subbrute doesn't kill the process after finishing the enumeration

### ISSUE THREAD

**Issue by aboul3la** [TheRook/subbrute#44]
Hey Mike,

I noticed that the latest version of subbrute hangs after finishing the enumeration and it doesn't kill or ends the process.

It hangs at this step: 

```
About to kill nameserver process... 
End
```

I hope you can fix this issue!
Thanks

**Comment by binarycanary** [comment]
This was a pain to track down, and I'm sorry I don't have the time at the moment to submit a proper PR.

For anyone experiencing this issue:
This appears to be happening because the `reeper` class is not terminating properly, OR because it is throwing some exception that isn't properly handled and the still open Python bug (http://bugs.python.org/issue9400) is hanging the process.

# Workaround/Fix:
The final messages printed, mentioned by @aboul3la above, happen at the end of the run method around lines 724-731 of `subbrute.py`. If you force `reeper` to terminate, the process will exit properly. That means adding the following code: `reeper.terminate()` at line 727 of `subbrute.py`:

```
    #We no longer require name servers.
    try:
        killproc(pid = verify_nameservers_proc.pid)
        reep.terminate() #ADDED THIS LINE HERE, EXITS PROPERLY
    except:
        #Windows threading.tread
        verify_nameservers_proc.end()
    trace("End")
```

If some kind soul could submit a proper pull request, or the tool author could do a quick update to master that would be great. Otherwise I will try to get something out in the next week so this is handled.

Cheers

**Comment by aboul3la** [comment]
Great job @binarycanary. Thanks a lot for your help!

**Comment by decidedlygray** [comment]
PR submitted for permanent fix: #48

**Comment by TheRook** [comment]
Due to this problem I have removed reeper entirely.  DNSLIb was still hanging on broken sockets.  I have updated DNSlib and more testing is needed.  

Thanks for your help!

**Comment by decidedlygray** [comment]
Oh cool! I was wondering if you might consider committing your development branch to github that has the dnslib updates and reeper removed?

At the moment, you can't integrate subbrute into any larger scripted solution because it never returns. I'm currently set up to use my own fork, so I can integrate with automation, but it would be nice to be using the official resource.
